const state = { data: null, lang: localStorage.getItem("bo-lang") || "en", theme: localStorage.getItem("bo-theme") || "dark", view: "leaderboard", sort: "release", direction: 1, detailX: "age", detailY: "raw", detailTimeline: "capability" };
const $ = id => document.getElementById(id);
const githubLink = document.createElement("a"); githubLink.className="github-link"; githubLink.href="https://github.com/yuema137/benchs-last-exam"; githubLink.target="_blank"; githubLink.rel="noreferrer"; githubLink.setAttribute("aria-label","GitHub repository"); githubLink.title="GitHub repository"; githubLink.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2C6.48 2 2 6.58 2 12.23c0 4.52 2.87 8.35 6.84 9.7.5.1.68-.22.68-.49 0-.24-.01-1.04-.01-1.89-2.78.62-3.37-1.22-3.37-1.22-.46-1.19-1.11-1.5-1.11-1.5-.91-.64.07-.63.07-.63 1 .07 1.52 1.06 1.52 1.06.9 1.58 2.35 1.12 2.92.86.09-.67.35-1.12.64-1.38-2.22-.26-4.56-1.14-4.56-5.06 0-1.12.39-2.03 1.02-2.75-.1-.26-.44-1.3.1-2.71 0 0 .84-.28 2.75 1.05A9.15 9.15 0 0 1 12 7.95c.85 0 1.7.12 2.5.36 1.91-1.33 2.75-1.05 2.75-1.05.54 1.41.2 2.45.1 2.71.63.72 1.02 1.63 1.02 2.75 0 3.93-2.35 4.8-4.58 5.05.36.32.68.94.68 1.9 0 .27-.01 2.47-.01 2.8 0 .27.18.59.69.49A10.24 10.24 0 0 0 22 12.23C22 6.58 17.52 2 12 2Z"/></svg>'; document.querySelector(".utility")?.append(githubLink);
const I18N = { en: { title:"Leaderboard of Benchmarks", lede:"Models are probes. The benchmark is the object we compare.", domain:"Domain", year:"Release year", filter:"Filter", coverage:"Coverage", all:"All", coverage_note:"ⓘ Coverage reflects representative frontier probes.", search:"Search benchmarks...", benchmark:"Benchmark", age:"Age", frontier:"Observed frontier", t50:"T50", t90:"T90", headroom:"Headroom", back:"← Back to leaderboard", released:"Released", metric:"Metric", observations:"source-linked observations", since:"Since release", calendar:"Calendar date", raw:"Raw score", normalized:"Normalized progress", what:"What it tests", task:"Task format", scoring:"How the score is calculated", target:"What the score measures", reference:"Reference-model coverage", history:"Historical frontier", resources:"Resources", benchmark_resources:"Benchmark resources", evidence_resources:"Model/evaluation resources used here", sources:"Sources and caveats", final:"final answer", environment:"environment outcome", process:"process and output", not_reached:"Not reached", unknown:"Unknown", na:"N/A", xaxis:"X axis", yaxis:"Y axis", plot_date:"Date used on this plot", date_meaning:"Date meaning", retrospective:"Retrospective evaluation; not a contemporaneous public result." }, zh: { title:"Leaderboard of Benchmarks", lede:"模型是测量探针，我们比较的是 benchmark 本身。", domain:"领域", year:"发布年份", filter:"筛选", coverage:"覆盖情况", all:"全部", coverage_note:"ⓘ Coverage 表示代表性 frontier models 是否测过这个 benchmark。", search:"搜索 benchmark...", benchmark:"Benchmark", age:"年龄", frontier:"已观测 frontier", t50:"T50", t90:"T90", headroom:"剩余 headroom", back:"← 返回 leaderboard", released:"发布于", metric:"Metric", observations:"条有来源的 observation", since:"发布后时间", calendar:"日历时间", raw:"原始分数", normalized:"Normalized progress", what:"这个 benchmark 测什么", task:"Task format", scoring:"评分方式", target:"分数测量什么", reference:"Reference-model coverage", history:"历史 frontier", resources:"资源", benchmark_resources:"Benchmark 资源", evidence_resources:"本页使用的模型/评测资源", sources:"来源和注意事项", final:"最终答案", environment:"环境结果", process:"过程和结果", not_reached:"尚未达到", unknown:"未知", na:"N/A", xaxis:"X 轴", yaxis:"Y 轴", plot_date:"本图使用的日期", date_meaning:"日期含义", retrospective:"回溯性评测；不代表当时已经公开的结果。" } };
I18N.en.velocity = "180d velocity";
I18N.zh.velocity = "180 天 velocity";
I18N.en.model = "Model"; I18N.zh.model = "Model";
I18N.en.score = "Score"; I18N.zh.score = "Score";
I18N.en.source = "Source"; I18N.zh.source = "来源";
I18N.en.model_released = "Model released"; I18N.zh.model_released = "Model 发布时间";
I18N.en.result_published = "Result published"; I18N.zh.result_published = "结果公开时间";
I18N.en.historical_result = "Historical result"; I18N.zh.historical_result = "历史公开结果";
I18N.en.timeline_unknown = "Historical status not established"; I18N.zh.timeline_unknown = "历史时间语义尚未确认";
I18N.en.retrospective_frontier = "Retrospective frontier"; I18N.zh.retrospective_frontier = "回溯性 frontier";
I18N.en.coverage_definition = "Coverage definition"; I18N.zh.coverage_definition = "Coverage 的计算方式";
I18N.en.coverage_formula = "Coverage is the share of the seven reference organizations below represented in this benchmark's curated observations. This is evidence coverage, not benchmark health or a count of all models."; I18N.zh.coverage_formula = "Coverage = 下面 7 个参考组织中，出现在这个 benchmark curated observations 里的组织数 ÷ 7。它表示证据覆盖，不代表 benchmark 健康程度，也不代表收集了多少模型。";
I18N.en.coverage_organizations = "Reference organizations"; I18N.zh.coverage_organizations = "参考组织";
I18N.en.evaluated_models = "Models represented in the observations"; I18N.zh.evaluated_models = "这些 observations 里出现的模型";
I18N.en.coverage_note = "ⓘ Coverage is the share of seven reference organizations represented in the curated observations. Open a row to see the models.";
I18N.zh.coverage_note = "ⓘ Coverage 是这个 benchmark 的 curated observations 中，出现过的 7 个参考组织所占比例。点击一行可以查看具体模型。";
I18N.en.frontier = "Capability frontier"; I18N.zh.frontier = "Capability frontier";
I18N.en.timeline = "Timeline"; I18N.zh.timeline = "时间线";
I18N.en.capability = "Capability"; I18N.zh.capability = "Capability";
I18N.en.reported = "Reported history"; I18N.zh.reported = "公开报告历史";
I18N.en.capability_event = "Capability frontier event"; I18N.zh.capability_event = "Capability frontier event";
I18N.en.retrospective_event = "Retrospective capability frontier event"; I18N.zh.retrospective_event = "回溯性 capability frontier 事件";
I18N.en.reported_event = "Reported frontier event"; I18N.zh.reported_event = "公开报告的 frontier 事件";
I18N.en.frontier_type = "Frontier type"; I18N.zh.frontier_type = "Frontier 类型";
I18N.en.model_release_date_meaning = "model release date"; I18N.zh.model_release_date_meaning = "model 发布时间";
I18N.en.public_date_meaning = "result first-public date"; I18N.zh.public_date_meaning = "结果首次公开日期";
I18N.en.raw_score = "Raw score"; I18N.zh.raw_score = "原始分数";
I18N.en.since_benchmark = "Since benchmark release"; I18N.zh.since_benchmark = "benchmark 发布后";
I18N.en.cost = "Cost / task"; I18N.zh.cost = "Cost / task";
I18N.en.cost_note = "Reported or explicitly derived from a documented full-run cost; varies by model and harness."; I18N.zh.cost_note = "该数值来自报告值，或按有明确 task 数量的 full-run cost 换算；实际成本会随 model 和 harness 变化。";
I18N.en.at_release = "At release"; I18N.zh.at_release = "At release";
I18N.en.evaluation_type = "Evaluation type"; I18N.zh.evaluation_type = "Evaluation type";
I18N.en.model_type = "Model"; I18N.zh.model_type = "Model";
I18N.en.agent_type = "Agent"; I18N.zh.agent_type = "Agent";
I18N.en.story = {"test-of-time":["Test of Time","Benchmarks that resisted model progress for at least a year to 50%, or two years to 90%."],"still-frontier":["Still Frontier","Benchmarks where the best observed capability has not yet reached 50%."],"fastest-solved":["Fastest Solved","Benchmarks that reached 90% capability within six months of release."],"recently-saturated":["Recently Saturated","Benchmarks that crossed 90% within the last three months."]};
I18N.zh.story = {"test-of-time":["时间考验","在达到 50% 前坚持至少一年，或达到 90% 前坚持至少两年的 benchmark。"],"still-frontier":["仍在前沿","目前观测到的最高 capability 还没有达到 50% 的 benchmark。"],"fastest-solved":["最快攻克","发布后六个月内就达到 90% 的 benchmark。"],"recently-saturated":["最近饱和","最近三个月内刚刚跨过 90% 的 benchmark。"]};
I18N.en.story_leaderboard = "Leaderboard"; I18N.zh.story_leaderboard = "排行榜";
I18N.en.story_frontier = "Current frontier"; I18N.zh.story_frontier = "当前 frontier";
I18N.en.story_below = "No evaluated model has reached 50%."; I18N.zh.story_below = "目前没有被测模型达到 50%。";
I18N.en.story_fast = "Reached 90% within six months of release."; I18N.zh.story_fast = "发布后六个月内达到 90%。";
I18N.en.story_recent = "90% crossing age"; I18N.zh.story_recent = "跨过 90% 的时间";
I18N.en.story_survived = "Still below this threshold."; I18N.zh.story_survived = "目前仍未达到这个阈值。";
I18N.en.story_took = "Time to reach this threshold."; I18N.zh.story_took = "达到这个阈值所用的时间。";
I18N.en.story_empty = "No benchmarks currently meet this definition."; I18N.zh.story_empty = "目前没有 benchmark 符合这个定义。";
const t = key => I18N[state.lang][key] || key;
const STORY_VIEWS = ["test-of-time", "still-frontier", "fastest-solved", "recently-saturated"];
const storyNav = document.createElement("nav"); storyNav.className = "story-tabs"; storyNav.setAttribute("aria-label", "Primary views");
storyNav.innerHTML = `<button class="story-tab" data-view="leaderboard">Leaderboard</button>${STORY_VIEWS.map(view => `<button class="story-tab" data-view="${view}"></button>`).join("")}`;
document.querySelector(".hero")?.after(storyNav);
const storyDescription = document.createElement("section"); storyDescription.id = "story-description"; storyDescription.className = "story-description"; storyDescription.hidden = true; storyNav.after(storyDescription);
const DOMAIN_LABELS = {"General knowledge & reasoning":"综合知识与推理", Mathematics:"数学", Science:"科学", Coding:"Coding", "Abstract reasoning":"抽象推理", Multimodal:"多模态", "Long context":"长上下文", "General agent tasks":"通用 agent 任务", "Software engineering":"软件工程", "Computer use":"Computer use", "Terminal / OS":"Terminal / OS", "Web / tool use":"Web / tool use", "Science / research":"科学 / research"};
const MODEL_DOMAINS = ["General knowledge & reasoning", "Mathematics", "Science", "Coding", "Abstract reasoning", "Multimodal", "Long context"];
const AGENT_DOMAINS = ["General agent tasks", "Software engineering", "Computer use", "Terminal / OS", "Web / tool use", "Science / research"];
const REFERENCE_ORGANIZATIONS = ["OpenAI", "Anthropic", "Google", "DeepSeek", "Qwen", "Meta", "xAI"];
const domainLabel = value => state.lang === "zh" ? (DOMAIN_LABELS[value] || value) : value;
const score = v => v == null ? "N/A" : `${(v * 100).toFixed(1)}%`;
const metricValue = (b, v) => v == null ? "N/A" : b.score_format === "number" ? Number(v).toFixed(0) : score(v);
const months = d => ((new Date(state.data.snapshot_id) - new Date(d)) / 86400000 / 30.44).toFixed(0);
const threshold = item => item.status === "reached" ? `${(item.days / 30.44).toFixed(1)} mo` : item.status === "at_release" ? t("at_release") : item.status === "right_censored" ? `≥ ${(item.days / 30.44).toFixed(0)} mo` : item.status === "not_applicable" ? t("na") : t("unknown");
const progress = (b, s) => b.floor == null || b.ceiling == null ? null : Math.max(0, Math.min(1, (s - b.floor) / (b.ceiling - b.floor)));
function frontierValue(b) { return b.capability_frontier_value ?? b.observed_frontier ?? b.current_frontier; }
function resourcesById() { return Object.fromEntries((state.data.resources || []).map(r=>[r.id,r])); }
function resourceList(ids) { const resources=resourcesById(); return [...new Set(ids || [])].map(id=>resources[id]).filter(Boolean); }
function resourceMarkup(resources) { return resources.length ? `<ul class="resource-list">${resources.map(r=>`<li><a href="${r.url}" target="_blank" rel="noreferrer">${r.title}</a><span class="small"> · ${r.publisher || r.authority}</span></li>`).join("")}</ul>` : `<p class="small">${t("unknown")}</p>`; }
function sortValue(b) { return { release: new Date(b.release).getTime(), current: frontierValue(b) ?? -1, headroom: b.normalized_headroom ?? 2, t50: b.threshold_days.T50.days ?? 1e9, t90: b.threshold_days.T90.days ?? 1e9, velocity: b.velocity_180d ?? -1, coverage: b.coverage.value, cost: b.cost_per_task?.value ?? null }[state.sort]; }
function updateDomainOptions() { const select=$("domain"), type=$("evaluation-type")?.value || "", allowed=type==="Model"?MODEL_DOMAINS:type==="Agent"?AGENT_DOMAINS:[...new Set((state.data?.benchmarks||[]).map(b=>b.domain))].sort(), current=select.value; select.innerHTML=`<option value="">${t("all")}</option>`+allowed.map(domain=>`<option value="${domain}">${domainLabel(domain)}</option>`).join(""); if(allowed.includes(current))select.value=current; }
function applyChrome() { document.documentElement.dataset.theme=state.theme; document.documentElement.lang=state.lang; $("page-title").textContent=t("title");$("page-lede").textContent=t("lede");$("search").placeholder=t("search");document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t(el.dataset.i18n));$("evaluation-type").options[0].text=t("all");$("evaluation-type").options[1].text=t("model_type");$("evaluation-type").options[2].text=t("agent_type");updateDomainOptions();$("year").options[0].text=t("all");$("coverage").options[0].text=t("all");$("lang-en").classList.toggle("active",state.lang==="en");$("lang-zh").classList.toggle("active",state.lang==="zh");$("theme-light").classList.toggle("active",state.theme==="light");$("theme-dark").classList.toggle("active",state.theme==="dark");document.querySelectorAll(".story-tab").forEach(tab=>{const view=tab.dataset.view;tab.textContent=view==="leaderboard"?t("story_leaderboard"):I18N[state.lang].story[view][0];tab.classList.toggle("active",state.view===view);}); }
function filtered() { const query=$("search").value.toLowerCase(), type=$("evaluation-type").value, domain=$("domain").value, year=$("year").value, rawCoverage=$("coverage").value.toLowerCase(), coverage=rawCoverage==="all"?"":rawCoverage; return state.data.benchmarks.filter(b=>(!query||`${b.name} ${b.domain} ${(b.tags||[]).join(" ")}`.toLowerCase().includes(query))&&(!type||b.evaluation_type===type)&&(!domain||b.domain===domain)&&(!year||b.release.slice(0,4)===year)&&(!coverage||b.coverage.status===coverage)).sort((a,b)=>{const av=sortValue(a),bv=sortValue(b);if(av==null&&bv==null)return 0;if(av==null)return 1;if(bv==null)return -1;return(av-bv)*state.direction;}); }
function header(label,key) { return `<button class="th-sort ${state.sort===key?"active":""}" data-sort="${key}">${label} ${state.sort===key?(state.direction===1?"↑":"↓"):"↕"}</button>`; }
function renderTable() { $("leaderboard").innerHTML=`<table><thead><tr><th>${header(t("benchmark"),"release")}</th><th>${t("domain")}</th><th>${header(t("age"),"release")}</th><th>${header(t("frontier"),"current")}</th><th>${header(t("t50"),"t50")}</th><th>${header(t("t90"),"t90")}</th><th>${header(t("headroom"),"headroom")}</th><th>${header(t("coverage"),"coverage")}</th></tr></thead><tbody>${filtered().map(b=>`<tr class="row-link" data-id="${b.id}"><td><strong>${b.name}</strong></td><td>${domainLabel(b.domain)}</td><td>${months(b.release)} mo</td><td>${metricValue(b,frontierValue(b))}</td><td>${threshold(b.threshold_days.T50)}</td><td>${threshold(b.threshold_days.T90)}</td><td>${b.normalized_headroom==null?t("na"):score(b.normalized_headroom)}</td><td><span class="coverage ${b.coverage.status}">${b.coverage.status}</span></td></tr>`).join("")}</tbody></table><p class="table-foot">Snapshot ${state.data.snapshot_id} · ${filtered().length} / ${state.data.benchmarks.length}</p>`; document.querySelectorAll("[data-sort]").forEach(el=>el.onclick=()=>{const key=el.dataset.sort;state.direction=state.sort===key?-state.direction:1;state.sort=key;renderTable();}); document.querySelectorAll(".row-link").forEach(el=>el.onclick=()=>showDetail(el.dataset.id)); }
renderTable = function() { const rows=filtered(); $("leaderboard").innerHTML=`<table><thead><tr><th>${header(t("benchmark"),"release")}</th><th>${t("domain")}</th><th>${header(t("age"),"release")}</th><th>${header(t("frontier"),"current")}</th><th>${header(t("t50"),"t50")}</th><th>${header(t("t90"),"t90")}</th><th>${header(t("headroom"),"headroom")}</th><th>${header(t("coverage"),"coverage")}</th><th>${header(t("cost"),"cost")}</th></tr></thead><tbody>${rows.map(b=>`<tr class="row-link" data-id="${b.id}"><td><strong>${b.name}</strong></td><td>${domainLabel(b.domain)}</td><td>${months(b.release)} mo</td><td>${metricValue(b,frontierValue(b))}</td><td>${threshold(b.threshold_days.T50)}</td><td>${threshold(b.threshold_days.T90)}</td><td>${b.normalized_headroom==null?t("na"):score(b.normalized_headroom)}</td><td><span class="coverage ${b.coverage.status}">${b.coverage.status}</span></td><td>${b.cost_per_task?`$${b.cost_per_task.value.toFixed(2)}`:"—"}</td></tr>`).join("")}</tbody></table><p class="table-foot">Snapshot ${state.data.snapshot_id} · ${rows.length} / ${state.data.benchmarks.length}</p>`; document.querySelectorAll("[data-sort]").forEach(el=>el.onclick=()=>{const key=el.dataset.sort;state.direction=state.sort===key?-state.direction:1;state.sort=key;renderTable();}); document.querySelectorAll(".row-link").forEach(el=>el.onclick=()=>showDetail(el.dataset.id)); };
function niceElapsedInterval(days) { const candidates=[1,2,3,7,14,30,60,90,182,365,730,1095,1825]; return candidates.reduce((best,v)=>Math.abs(days/v-10)<Math.abs(days/best-10)?v:best,candidates[0]); }
function elapsedLabel(days) { if(days<365)return`${Math.round(days)}d`; const years=Math.floor(days/365.25);const months=Math.round((days-years*365.25)/30.44);if(months>=12)return`${years+1} yr`;return months?`${years} yr ${months} mo`:`${years} yr`; }
function calendarTicks(start,end) { const span=(end-start)/86400000, step=span>1825?"year":span>730?"quarter":span>120?"month":span>35?"week":"day", ticks=[], d=new Date(start); if(step==="year")d.setUTCMonth(0,1);else if(step==="quarter")d.setUTCMonth(Math.floor(d.getUTCMonth()/3)*3,1);else if(step==="month")d.setUTCDate(1);else if(step==="week")d.setUTCDate(d.getUTCDate()-d.getUTCDay());else d.setUTCHours(0,0,0,0); while(d<=end){ticks.push({date:new Date(d),label:step==="year"?`${d.getUTCFullYear()}`:d.toLocaleDateString(state.lang==="zh"?"zh-CN":"en-US",step==="month"?{month:"short",year:"numeric"}:step==="quarter"?{month:"short",year:"numeric"}:{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"})}); if(step==="year")d.setUTCFullYear(d.getUTCFullYear()+1);else if(step==="quarter")d.setUTCMonth(d.getUTCMonth()+3);else if(step==="month")d.setUTCMonth(d.getUTCMonth()+1);else if(step==="week")d.setUTCDate(d.getUTCDate()+7);else d.setUTCDate(d.getUTCDate()+1);} return ticks; }
function compactTicks(ticks,xDate,min,max) { const sorted=ticks.filter(q=>q.date>=min&&q.date<=max).sort((a,b)=>a.date-b.date); const result=[]; for(const tick of sorted) { if(!result.length || xDate(tick.date)-xDate(result[result.length-1].date)>=48) result.push(tick); } if(sorted.length && result[result.length-1].date.getTime()!==sorted[sorted.length-1].date.getTime() && xDate(sorted[sorted.length-1].date)-xDate(result[result.length-1].date)>=48) result.push(sorted[sorted.length-1]); return result; }
function tooltipMarkup(b,p,timeline) { const source=resourceList(p.source_ids||[])[0]; const observation=(b.observations||[]).find(item=>item.observation_id===p.observation_id)||p; const plotDate=observation.capability_date||observation.plot_date||observation.date; const since=((new Date(plotDate)-new Date(`${b.release}T00:00:00Z`))/86400000/30.44); const elapsed=since>=12?`${Math.floor(since/12)} yr${Math.round(since%12)?` ${Math.round(since%12)} mo`:``}`:`${Math.round(since)} mo`; const eventType=timeline==="capability"?(observation.retrospective?t("retrospective_event"):t("capability_event")):t("reported_event"); const raw=metricValue(b,observation.score); const normalized=progress(b,observation.score); const dateLabel=timeline==="capability"?t("model_release_date_meaning"):t("public_date_meaning"); return `<strong>${observation.model}</strong><span>${t("frontier_type")}: ${eventType}</span><span>${t("score")}: <b>${state.detailY==="normalized"&&normalized!=null?score(normalized):raw}</b></span>${state.detailY==="normalized"&&normalized!=null?`<span>${t("raw_score")}: ${raw}</span>`:""}<span>${t("plot_date")}: ${plotDate||t("unknown")}</span><span>${t("date_meaning")}: ${dateLabel}</span><span>${t("model_released")}: ${observation.model_release_date||t("unknown")}</span><span>${t("since_benchmark")}: ${elapsed}</span>${observation.result_public_date?`<span>${t("result_published")}: ${observation.result_public_date}</span>`:""}<a href="${source?.url||observation.source||"#"}" target="_blank" rel="noreferrer">${t("source")}: ${source?.title||observation.source||t("unknown")}</a>`; }
function chart(b) { const timeline=state.detailTimeline,pts=timeline==="capability"?(b.capability_frontier||b.frontier_events||[]):(b.reported_frontier||[]),W=760,H=340,L=58,R=18,T=22,B=92,plotBottom=H-B,plotRight=W-R,min=new Date(`${b.release}T00:00:00Z`),max=new Date(`${state.data.snapshot_id}T00:00:00Z`),span=Math.max(1,(max-min)/86400000),xDate=d=>L+((new Date(d)-min)/(max-min||1))*(plotRight-L),value=p=>state.detailY==="normalized"?(progress(b,p.score)??p.score):p.score,yValue=v=>T+(1-v)*(plotBottom-T),x=d=>xDate(d),y=p=>yValue(value(p)),rawTicks=state.detailX==="age"?Array.from({length:Math.ceil(span/niceElapsedInterval(span))+1},(_,i)=>{const days=Math.min(i*niceElapsedInterval(span),span);return{date:new Date(min.getTime()+days*86400000),label:elapsedLabel(days)}}):calendarTicks(min,max),xTicks=compactTicks(rawTicks,xDate,min,max),labels=xTicks.map(q=>q.label);if(new Set(labels).size!==labels.length)throw new Error(`Duplicate chart tick labels for ${b.name}`);const grid=xTicks.map(q=>`<line class="gridline" x1="${x(q.date)}" y1="${T}" x2="${x(q.date)}" y2="${plotBottom}"/><text class="axis-text x-label" text-anchor="middle" x="${x(q.date)}" y="${plotBottom+18}">${q.label}</text>`).join(""),yTicks=[0,.2,.4,.6,.8,1],ygrid=yTicks.map(v=>`<line class="gridline" x1="${L}" y1="${yValue(v)}" x2="${plotRight}" y2="${yValue(v)}"/><text class="axis-text" text-anchor="end" x="${L-9}" y="${yValue(v)+4}">${Math.round(v*100)}%</text>`).join(""); let path="";if(pts.length){path=`M${x(pts[0].plot_date||pts[0].date)},${y(pts[0])}`;for(let i=1;i<pts.length;i++)path+=`H${x(pts[i].plot_date||pts[i].date)}V${y(pts[i])}`;path+=`H${x(max.toISOString())}`;}const dots=pts.map(p=>`<g class="frontier-point"><circle class="dot ${timeline}" cx="${x(p.plot_date||p.date)}" cy="${y(p)}" r="4"/><circle class="frontier-hit" tabindex="0" role="button" aria-label="${p.model} ${score(p.score)}" data-observation-id="${p.observation_id}" cx="${x(p.plot_date||p.date)}" cy="${y(p)}" r="17"/></g>`).join("");const clipId=`clip-${b.id}`;return`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${timeline} frontier for ${b.name}"><defs><clipPath id="${clipId}"><rect x="${L}" y="${T}" width="${plotRight-L}" height="${plotBottom-T}"/></clipPath></defs>${grid}${ygrid}<line class="axis-line" x1="${L}" y1="${plotBottom}" x2="${plotRight}" y2="${plotBottom}"/><g clip-path="url(#${clipId})"><path class="curve" d="${path}"/>${dots}</g><text class="axis-title" text-anchor="middle" x="${(L+plotRight)/2}" y="${H-30}">${state.detailX==="age"?t("since"):t("calendar")}</text><text class="axis-title" text-anchor="middle" transform="translate(13 ${(T+plotBottom)/2}) rotate(-90)">${state.detailY==="normalized"?t("normalized"):t("raw")}</text></svg>`; }
const ratioChart = chart;
function numericChart(b) { const timeline=state.detailTimeline,pts=timeline==="capability"?(b.capability_frontier||b.frontier_events||[]):(b.reported_frontier||[]),W=760,H=340,L=58,R=18,T=22,B=92,plotBottom=H-B,plotRight=W-R,min=new Date(`${b.release}T00:00:00Z`),max=new Date(`${state.data.snapshot_id}T00:00:00Z`),values=pts.map(p=>p.score),rawMin=Math.min(...values),rawMax=Math.max(...values),padding=Math.max(1,(rawMax-rawMin)*.12),yMin=Math.floor((rawMin-padding)/10)*10,yMax=Math.ceil((rawMax+padding)/10)*10,xDate=d=>L+((new Date(d)-min)/(max-min||1))*(plotRight-L),yValue=v=>T+(yMax-v)/(yMax-yMin)*(plotBottom-T),x=d=>xDate(d),y=p=>yValue(p.score),rawTicks=state.detailX==="age"?Array.from({length:Math.ceil((max-min)/86400000/niceElapsedInterval((max-min)/86400000))+1},(_,i)=>{const days=Math.min(i*niceElapsedInterval((max-min)/86400000),(max-min)/86400000);return{date:new Date(min.getTime()+days*86400000),label:elapsedLabel(days)}}):calendarTicks(min,max),xTicks=compactTicks(rawTicks,xDate,min,max),grid=xTicks.map(q=>`<line class="gridline" x1="${x(q.date)}" y1="${T}" x2="${x(q.date)}" y2="${plotBottom}"/><text class="axis-text x-label" text-anchor="middle" x="${x(q.date)}" y="${plotBottom+18}">${q.label}</text>`).join(""),yTicks=Array.from({length:5},(_,i)=>yMin+(yMax-yMin)*i/4),ygrid=yTicks.map(v=>`<line class="gridline" x1="${L}" y1="${yValue(v)}" x2="${plotRight}" y2="${yValue(v)}"/><text class="axis-text" text-anchor="end" x="${L-9}" y="${yValue(v)+4}">${Math.round(v)}</text>`).join(""),path=pts.length?`M${x(pts[0].plot_date||pts[0].date)},${y(pts[0])}`+pts.slice(1).map(p=>`H${x(p.plot_date||p.date)}V${y(p)}`).join("")+`H${x(max.toISOString())}`:"",dots=pts.map(p=>`<g class="frontier-point"><circle class="dot ${timeline}" cx="${x(p.plot_date||p.date)}" cy="${y(p)}" r="4"/><circle class="frontier-hit" tabindex="0" role="button" aria-label="${p.model} ${metricValue(b,p.score)}" data-observation-id="${p.observation_id}" cx="${x(p.plot_date||p.date)}" cy="${y(p)}" r="17"/></g>`).join(""),clipId=`clip-${b.id}-numeric`;return`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${timeline} frontier for ${b.name}"><defs><clipPath id="${clipId}"><rect x="${L}" y="${T}" width="${plotRight-L}" height="${plotBottom-T}"/></clipPath></defs>${grid}${ygrid}<line class="axis-line" x1="${L}" y1="${plotBottom}" x2="${plotRight}" y2="${plotBottom}"/><g clip-path="url(#${clipId})"><path class="curve" d="${path}"/>${dots}</g><text class="axis-title" text-anchor="middle" x="${(L+plotRight)/2}" y="${H-30}">${state.detailX==="age"?t("since"):t("calendar")}</text><text class="axis-title" text-anchor="middle" transform="translate(13 ${(T+plotBottom)/2}) rotate(-90)">${t("raw")}</text></svg>`; }
chart = function(b) { return b.score_format === "number" ? numericChart(b) : ratioChart(b); };
// Keep edge events visible: the plot data layer gets a small horizontal safety margin.
const chartWithSafetyMargin=chart;
function keepBoundaryMarkersVisible(svg) {
  // A capability event at benchmark release is validly plotted at x=0.
  // Inset only the marker/hit target by a few SVG units so its radius is not
  // half-hidden by the left border; the observation retains its real date.
  return svg
    .replace(/(<circle class="dot [^"]+" cx=")58"/g, '$166"')
    .replace(/(<circle class="frontier-hit"[^>]*cx=")58"/g, '$166"');
}
chart=function(b) { if(state.detailTimeline==="capability" && !(b.capability_frontier||b.frontier||[]).length) return `<svg viewBox="0 0 760 340" role="img" aria-label="${state.detailY} frontier for ${b.name}"></svg>`; return keepBoundaryMarkersVisible(chartWithSafetyMargin(b).replace(/<rect x="58" y="22" width="684" height="226"\/>/, '<rect x="50" y="22" width="700" height="226"/>')); };
function showLeaderboard(event) {
  event?.preventDefault();
  if (!state.data) return;
  state.view="leaderboard"; state.sort="current"; state.direction=1;
  document.querySelectorAll(".story-tab").forEach(tab=>tab.classList.toggle("active",tab.dataset.view==="leaderboard"));
  ["search","evaluation-type","domain","year","coverage"].forEach(id=>{if($(id))$(id).value="";});
  $("controls").hidden=false;
  $("leaderboard").hidden=false;
  $("detail").hidden=true;
  $("page-title").textContent=t("title");
  $("page-lede").textContent=t("lede");
  renderTable();
}
function routeToLeaderboard(event) { event?.preventDefault(); history.pushState({page:"leaderboard"},"",`${location.pathname}#leaderboard`); showLeaderboard(event); }
function thresholdDays(b, key) { const item=b.threshold_days?.[key]; return item?.days == null ? null : item.days; }
function reached(b, key) { return ["reached", "at_release"].includes(b.threshold_days?.[key]?.status); }
function storyMembers(view) {
  const members=new Set(state.data.lifecycle_views?.[view]||[]);
  return state.data.benchmarks.filter(b=>members.has(b.id)).sort((a,b)=>{
    if(view==="still-frontier") return (a.normalized_progress??2)-(b.normalized_progress??2);
    if(view==="fastest-solved") return thresholdDays(a,"T90")-thresholdDays(b,"T90");
    if(view==="recently-saturated") return thresholdDays(b,"T90")-thresholdDays(a,"T90");
    return Math.max(thresholdDays(b,"T90")??0,thresholdDays(b,"T50")??0)-Math.max(thresholdDays(a,"T90")??0,thresholdDays(a,"T50")??0);
  });
}
function storyHero(b,view) { const t90=b.threshold_days.T90, t50=b.threshold_days.T50;
  if(view==="still-frontier") return [t("story_frontier"),metricValue(b,frontierValue(b)),t("story_below")];
  if(view==="fastest-solved") return [t("t90"),threshold(t90),t("story_fast")];
  if(view==="recently-saturated") return [t("story_crossing"),threshold(t90),t("story_recent")];
  const item=t90?.days>=24*30.44*86400000?t90:t50; return [item===t90?t("t90"):t("t50"),threshold(item),item?.status==="right_censored"?t("story_survived"):t("story_took")];
}
function storyCard(b,view) { const [hero,value,statement]=storyHero(b,view); const longevity=view==="test-of-time"?`<span>${t("t50")} <b>${threshold(b.threshold_days.T50)}</b></span><span>${t("t90")} <b>${threshold(b.threshold_days.T90)}</b></span>`:""; return `<article class="story-card" data-id="${b.id}"><div class="story-card-head"><div><h2>${b.name}</h2><p class="domain">${b.evaluation_type} · ${domainLabel(b.domain)}</p></div><span class="coverage ${b.coverage.status}">${b.coverage.status}</span></div><div class="story-hero"><span>${hero}</span><strong>${value}</strong><p>${statement}</p></div><div class="story-support">${longevity}<span>${t("age")} <b>${months(b.release)} mo</b></span><span>${t("frontier")} <b>${metricValue(b,frontierValue(b))}</b></span><span>${t("coverage")} <b>${Math.round((b.coverage.value||0)*100)}%</b></span></div></article>`; }
function renderStory() { const view=state.view, [title,description]=I18N[state.lang].story[view]; storyDescription.hidden=false; storyDescription.innerHTML=`<h2>${title}</h2><p>${description}</p>`; $("controls").hidden=true; $("leaderboard").hidden=false; $("detail").hidden=true; $("leaderboard").className="story-grid"; const rows=storyMembers(view); $("leaderboard").innerHTML=rows.length?rows.map(b=>storyCard(b,view)).join(""):`<p class="notice">${t("story_empty")}</p>`; document.querySelectorAll(".story-card").forEach(card=>card.onclick=()=>showDetail(card.dataset.id)); document.querySelectorAll(".story-tab").forEach(tab=>tab.classList.toggle("active",tab.dataset.view===view)); }
function renderCurrentView() { if(state.view==="leaderboard") renderTable(); else renderStory(); }
function bindChartInteractions(b) { const wrapper=document.querySelector(".detail-chart"); const svg=wrapper?.querySelector("svg"); const tooltip=wrapper?.querySelector(".chart-tooltip"); if(!svg||!tooltip)return; const points=[...(svg.querySelectorAll(".frontier-hit"))]; const show=(hit,event)=>{ points.forEach(item=>item.parentElement.classList.toggle("is-hovered",item===hit)); const point=(b.capability_frontier||[]).find(item=>item.observation_id===hit.dataset.observationId)||(b.reported_frontier||[]).find(item=>item.observation_id===hit.dataset.observationId); if(!point)return; tooltip.innerHTML=tooltipMarkup(b,point,state.detailTimeline); tooltip.hidden=false; const rect=wrapper.getBoundingClientRect(),svgRect=svg.getBoundingClientRect(),sx=svgRect.width/760,sy=svgRect.height/340,px=svgRect.left-rect.left+Number(hit.getAttribute("cx"))*sx,py=svgRect.top-rect.top+Number(hit.getAttribute("cy"))*sy; const tw=tooltip.offsetWidth,th=tooltip.offsetHeight; const left=Math.max(8,Math.min(wrapper.clientWidth-tw-8,px+18)); const top=py-th-14>=8?py-th-14:Math.min(wrapper.clientHeight-th-8,py+18); tooltip.style.left=`${left}px`;tooltip.style.top=`${Math.max(8,top)}px`; }; points.forEach(hit=>{hit.addEventListener("mouseenter",event=>show(hit,event));hit.addEventListener("focus",event=>show(hit,event));hit.addEventListener("mouseleave",()=>{hit.parentElement.classList.remove("is-hovered");tooltip.hidden=true});hit.addEventListener("blur",()=>{hit.parentElement.classList.remove("is-hovered");tooltip.hidden=true});}); }
function showDetail(id) {
  const b=state.data.benchmarks.find(x=>x.id===id);
  if(!b){
    $("controls").hidden=true;$("leaderboard").hidden=true;$("detail").hidden=false;
    $("page-title").textContent=t("unknown");
    $("page-lede").innerHTML="<a href=\"#leaderboard\" id=\"back-link\">"+t("back")+"</a>";
    $("detail").innerHTML="<p class=\"notice\">"+t("unknown")+"</p>";
    $("back-link").onclick=routeToLeaderboard;
    return;
  }
  $("controls").hidden=true;$("leaderboard").hidden=true;$("detail").hidden=false;
  $("page-title").textContent=b.name;
  $("page-lede").innerHTML=`<a href="#leaderboard" id="back-link">${t("back")}</a> · ${domainLabel(b.domain)} · ${t("released")} ${b.release} · Age ${months(b.release)} mo`;
  const benchmarkResources=resourceList(b.resource_ids);
  const evidenceIds=(b.capability_frontier||b.frontier||[]).flatMap(p=>p.source_ids||[]).filter(sourceId=>!b.resource_ids.includes(sourceId));
  const evidenceResources=resourceList(evidenceIds);
  const timeline=state.detailTimeline;
  const timelinePoints=timeline==="capability"?(b.capability_frontier||b.frontier||[]):(b.reported_frontier||[]);
  const timelineEmpty=timeline==="reported"&&!timelinePoints.length?`<p class="notice">${state.lang==="zh"?"公开报告 frontier 暂不可用。当前数据不足以重建按结果首次公开时间排列的可比历史 frontier。":"Reported frontier unavailable. The current data is not sufficient to reconstruct a comparable frontier by first-public result date."}</p>`:"";
  const representedModels=[...new Map(b.observations.map(item=>[item.model_id,item])).values()].sort((a,z)=>a.model.localeCompare(z.model));
  $("detail").innerHTML=`<div class="detail-head"><span class="coverage ${b.coverage.status}">${b.coverage.status} ${t("coverage").toLowerCase()}</span><span class="small">${t("metric")}: ${b.metric} · ${b.observation_count} ${t("observations")}</span></div><section class="overview"><h2>${t("what")}</h2><p>${b.summary[state.lang]}</p><h2>${t("task")}</h2><p>${b.task_format[state.lang]}</p><h2>${t("scoring")}</h2><p><strong>${b.scoring.metric_name}</strong> — ${b.scoring.explanation[state.lang]}</p><h2>${t("target")}</h2><p>${b.evaluation_target==="environment_outcome"?t("environment"):b.evaluation_target==="process_and_output"?t("process"):t("final")}</p></section><div class="detail-controls"><label>${t("timeline")} <select id="detail-timeline"><option value="capability">${t("capability")}</option><option value="reported">${t("reported")}</option></select></label><label>${t("xaxis")} <select id="detail-x"><option value="age">${t("since")}</option><option value="calendar">${t("calendar")}</option></select></label><label>${t("yaxis")} <select id="detail-y"><option value="raw">${t("raw")}</option><option value="normalized">${t("normalized")}</option></select></label></div><div class="detail-chart">${chart(b)}<div class="chart-tooltip" role="status" hidden></div>${timelineEmpty}</div><div class="detail-kpis"><div><span>${t("frontier")}</span><strong>${metricValue(b,frontierValue(b))}</strong></div><div><span>${t("headroom")}</span><strong>${b.normalized_headroom==null?t("na"):score(b.normalized_headroom)}</strong></div><div><span>${t("t50")}</span><strong>${threshold(b.threshold_days.T50)}</strong></div><div><span>${t("t90")}</span><strong>${threshold(b.threshold_days.T90)}</strong></div><div><span>${t("velocity")}</span><strong>${b.velocity_180d==null?t("na"): `${(b.velocity_180d*100).toFixed(1)} pp/mo`}</strong></div><div><span>${t("coverage")}</span><strong>${Math.round(b.coverage.value*100)}%</strong></div></div><h2>${t("reference")}</h2><p class="small">${b.coverage.represented_organizations.join(", ")||t("unknown")}</p><h2>${t("resources")}</h2><h3>${t("benchmark_resources")}</h3>${resourceMarkup(benchmarkResources)}<h3>${t("evidence_resources")}</h3>${resourceMarkup(evidenceResources)}<h2>${t("history")}</h2><div class="provenance">${timelinePoints.slice().reverse().map(p=>`<div><strong>${p.plot_date||p.date}</strong> · ${p.model} · ${metricValue(b,p.score)}<br><span class="small">${t("plot_date")}: ${p.plot_date||p.date} · ${t("date_meaning")}: ${timeline==="capability"?t("model_release_date_meaning"):t("public_date_meaning")}</span>${p.retrospective?`<br><span class="small">${t("retrospective")}</span>`:""}<br>${resourceMarkup(resourceList(p.source_ids||[]))}</div>`).join("")}</div><h2>${t("sources")}</h2><p class="caveat">${b.date_policy}</p>`;
  const costKpi=document.createElement("div"); costKpi.innerHTML=`<span>${t("cost")}</span><strong>${b.cost_per_task?`$${b.cost_per_task.value.toFixed(2)}`:"—"}</strong>`; $("detail").querySelector(".detail-kpis")?.appendChild(costKpi);
  if(b.cost_per_task){ const costNote=document.createElement("p"); costNote.className="caveat"; costNote.textContent=`${t("cost_note")} ${b.cost_per_task.method}.`; $("detail").querySelector(".detail-kpis")?.after(costNote); }
  const coverageExplanation=document.createElement("section"); coverageExplanation.className="coverage-explanation"; coverageExplanation.innerHTML=`<h2>${t("coverage_definition")}</h2><p class="small">${t("coverage_formula")}</p><h3>${t("coverage_organizations")}</h3><ul class="coverage-panel">${REFERENCE_ORGANIZATIONS.map(org=>{const represented=b.coverage.represented_organizations.includes(org);return`<li class="${represented?"represented":"missing"}"><span aria-hidden="true">${represented?"✓":"—"}</span>${org}</li>`}).join("")}</ul><details class="coverage-models"><summary>${t("evaluated_models")} (${representedModels.length})</summary><p class="small">${representedModels.map(item=>item.model).join(", ")||t("unknown")}</p></details>`; $("detail").insertBefore(coverageExplanation,$("detail").querySelector(".detail-controls"));
  $("detail-timeline").value=state.detailTimeline;$("detail-x").value=state.detailX;$("detail-y").value=state.detailY;$("detail-timeline").onchange=e=>{state.detailTimeline=e.target.value;showDetail(id)};$("detail-x").onchange=e=>{state.detailX=e.target.value;showDetail(id)};$("detail-y").onchange=e=>{state.detailY=e.target.value;showDetail(id)};bindChartInteractions(b);
  $("back-link").onclick=routeToLeaderboard;
}
const renderLeaderboardTable = renderTable;
renderTable = function(){ if(state.view!=="leaderboard") return renderStory(); $("story-description").hidden=true; $("leaderboard").className="table-wrap"; return renderLeaderboardTable(); };
storyNav.addEventListener("click", event=>{const tab=event.target.closest(".story-tab");if(!tab||!state.data)return;state.view=tab.dataset.view;if(state.view==="leaderboard")showLeaderboard(event);else{history.pushState({page:state.view},"",`${location.pathname}#${state.view}`);$("controls").hidden=true;$("detail").hidden=true;renderStory();}});
function setLang(lang){state.lang=lang;localStorage.setItem("bo-lang",lang);applyChrome();if($("detail").hidden)renderTable();else{const id=state.data.benchmarks.find(b=>b.name===$("page-title").textContent)?.id;if(id)showDetail(id);}}
function setTheme(theme){state.theme=theme;localStorage.setItem("bo-theme",theme);applyChrome();}
$("lang-en").onclick=()=>setLang("en");$("lang-zh").onclick=()=>setLang("zh");$("theme-light").onclick=()=>setTheme("light");$("theme-dark").onclick=()=>setTheme("dark");
$("evaluation-type").addEventListener("change",()=>{updateDomainOptions();});
window.addEventListener("popstate",()=>{if(location.hash==="#leaderboard"||location.hash==="")showLeaderboard();else if(STORY_VIEWS.includes(location.hash.slice(1))){state.view=location.hash.slice(1);renderStory();}});
window.addEventListener("hashchange",()=>{if(location.hash==="#leaderboard")showLeaderboard();else if(STORY_VIEWS.includes(location.hash.slice(1))){state.view=location.hash.slice(1);renderStory();}});
$("apply-filters").addEventListener("click",event=>{event.preventDefault();state.sort="current";state.direction=1;renderTable();});
state.sort="current"; state.direction=1;
fetch("data/benchmarks.json?v=20260903-5").then(r=>r.json()).then(data=>{state.data=data;applyChrome();[...new Set(data.benchmarks.map(b=>b.release.slice(0,4)))].sort().forEach(y=>$("year").insertAdjacentHTML("beforeend",`<option>${y}</option>`));renderTable();}).catch(e=>$("leaderboard").innerHTML=`<p class="notice">${e}</p>`);
